version: 2

jobs:
  build:etl:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      
      - run:
          name: Spin up virtual env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r "requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Check code quality
          command: |
            . venv/bin/activate
            flake8 etl.py create_tables.py
            black etl.py create_tables.py --check
            isort etl.py create_tables.py --check-only